version : '3.3'
services :
  mango:
    ports:
      - '27017:27017'
    container_name: demo_mongo
    restart: on-failure
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mangoadmin
      - MONGO_INITDB_ROOT_PASSWORD=password
    image: mongo